version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports: 
      - 2379:2379
    volumes:
      - etcd_data:/bitnami/etcd
volumes:
  etcd_data:
    driver: local


# etcdctl --endpoints=127.0.0.1:2379 put foo "Hello World"