version: '2'

services:
  apollo-quick-start:
    image: nobodyiam/apollo-quick-start
    container_name: apollo-quick-start
    ports:
      - "28080:8080"
      - "28090:8090"
      - "28070:8070"
    links:
      - apollo-db

  apollo-db:
    image: mysql:5.7
    container_name: apollo-db
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "23306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - /Users/m-mac-wl1-055/sql/apollo:/var/lib/mysql

  # apollo-dbdata:
  #   image: alpine:latest
  #   container_name: apollo-dbdata
  #   volumes:
  #     - /var/lib/mysql