version: '3'

services:
  kafka1:
    working_dir: ${WORKDIR}
    image: wurstmeister/kafka:2.13-2.7.0
    depends_on:
    - zoo1
    - zoo2
    - zoo3
    ports:
      - "${KAFKA1_PORT}:9092"
    environment:
      KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: test:6:1
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}

  # kafka2:
  #   working_dir: ${WORKDIR}
  #   image: wurstmeister/kafka:2.13-2.7.0
  #   depends_on:
  #     - zoo1
  #     - zoo2
  #     - zoo3
  #   ports:
  #     - "${KAFKA2_PORT}:9092"
  #   environment:
  #     KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
  #     KAFKA_ADVERTISED_PORT: 9093
  #     KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}

  # kafka3:
  #   working_dir: ${WORKDIR}
  #   image: wurstmeister/kafka:2.13-2.7.0
  #   depends_on:
  #   - zoo1
  #   - zoo2
  #   - zoo3
  #   ports:
  #     - "${KAFKA3_PORT}:9092"
  #   environment:
  #     KAFKA_LOG_DIRS: ${KAFKA_LOG_DIRS}
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
  #     KAFKA_ADVERTISED_PORT: 9094
  #     KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}

  zoo1:
    image: zookeeper:3.7
    hostname: zoo1
    container_name: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ports:
      - "${ZOO1_PORT}:2181"
    #   - "18081:8080"

  zoo2:
    image: zookeeper:3.7
    hostname: zoo2
    container_name: zoo2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181 server.3=zoo3:2888:3888;2181
    ports:
      - "${ZOO2_PORT}:2181"
    #   - "18082:8080"
  
  zoo3:
    image: zookeeper:3.7
    hostname: zoo3
    container_name: zoo3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=0.0.0.0:2888:3888;2181
    ports:
      - "${ZOO3_PORT}:2181"
    #   - "18083:8080" 